#!/usr/bin/env sh
#
# Gradle start up script for POSIX generated by Gradle.
#

# Resolve links: $0 may be a link
PRG="$0"

while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")/"$link"
  fi
done

SAVED="`pwd`"
cd "`dirname \"$PRG\"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

DEFAULT_JVM_OPTS='"-Xmx1024m" "-Xms256m"'
MAX_FD=maximum

warn() {
  echo "$*" >&2
}

die() {
  echo
  echo "$*" >&2
  echo
  exit 1
}

cygwin=false
msys=false
darwin=false
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  MINGW* ) msys=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ]; then
  if [ -x "$JAVA_HOME/jre/sh/java" ]; then
    JAVACMD=$JAVA_HOME/jre/sh/java
  else
    JAVACMD=$JAVA_HOME/bin/java
  fi
  if [ ! -x "$JAVACMD" ]; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
  fi
else
  JAVACMD=java
  which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and java not found in PATH"
fi

if [ "$cygwin" = false ] && [ "$darwin" = false ] && [ "$msys" = false ]; then
  MAX_FD_LIMIT=$(ulimit -H -n)
  if [ $? -eq 0 ]; then
    if [ "$MAX_FD" = maximum ] || [ "$MAX_FD" = max ]; then
      MAX_FD="$MAX_FD_LIMIT"
    fi
    ulimit -n $MAX_FD || warn "Could not set file descriptor limit: $MAX_FD"
  else
    warn "Could not query max file descriptor limit"
  fi
fi

if $darwin; then
  GRADLE_OPTS="$GRADLE_OPTS -Xdock:name=$APP_NAME -Xdock:icon=$APP_HOME/media/gradle.icns"
fi

if $cygwin || $msys; then
  APP_HOME=$(cygpath --path --mixed "$APP_HOME")
  CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
  JAVACMD=$(cygpath --unix "$JAVACMD")
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
